'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('stereo', {
  isReal: true,
  scan: () => ipcRenderer.invoke('scan'),
  scanDrive: (drive) => ipcRenderer.invoke('scanDrive', drive),
  drives: () => ipcRenderer.invoke('drives'),
  openFolder: (dir) => ipcRenderer.invoke('openFolder', dir),
  listExes: (dir) => ipcRenderer.invoke('listExes', dir),
  fetchIcon: (name) => ipcRenderer.invoke('fetchIcon', name),
  buildInfo: () => ipcRenderer.invoke('buildInfo'),
  rateLimitState: () => ipcRenderer.invoke('rateLimitState'),
  clearGhCache: () => ipcRenderer.invoke('clearGhCache'),
  icon: (exePath) => ipcRenderer.invoke('icon', exePath),
  pickExe: () => ipcRenderer.invoke('pickExe'),

  coreList: () => ipcRenderer.invoke('coreList'),
  postInstallInfo: (game, modId) => ipcRenderer.invoke('postInstallInfo', game, modId),
  runPostInstall: (game, modId) => ipcRenderer.invoke('runPostInstall', game, modId),
  coreSources: () => ipcRenderer.invoke('coreSources'),
  coreFetch: (modId, game) => ipcRenderer.invoke('coreFetch', modId, game),
  coreFetchAll: () => ipcRenderer.invoke('coreFetchAll'),
  coreUpdate: (modId, game) => ipcRenderer.invoke('coreUpdate', modId, game),
  coreRoot: () => ipcRenderer.invoke('coreRoot'),
  openCoreFolder: (id) => ipcRenderer.invoke('openCoreFolder', id),
  checkUpdates: () => ipcRenderer.invoke('checkUpdates'),
  htMatch: (games) => ipcRenderer.invoke('htMatch', games),
  appVersion: () => ipcRenderer.invoke('appVersion'),
  appUpdateCheck: () => ipcRenderer.invoke('appUpdateCheck'),
  appUpdateDownload: (asset) => ipcRenderer.invoke('appUpdateDownload', asset),
  setupDgVoodoo: (game, opts) => ipcRenderer.invoke('setupDgVoodoo', game, opts),
  applyDx9Proxy: (game) => ipcRenderer.invoke('applyDx9Proxy', game),
  htVersionsFor: (entry) => ipcRenderer.invoke('htVersionsFor', entry),
  htInstallManual: (entry, game, version) => ipcRenderer.invoke('htInstallManual', entry, game, version),
  htCatalog: (force) => ipcRenderer.invoke('htCatalog', force),
  checkHeadTracking: (games) => ipcRenderer.invoke('checkHeadTracking', games),
  downloadHeadTracking: (ids) => ipcRenderer.invoke('downloadHeadTracking', ids),
  latest: (modId, game) => ipcRenderer.invoke('latest', modId, game),

  install: (modId, game, opts) => ipcRenderer.invoke('install', modId, game, opts),
  hubVersions: (game) => ipcRenderer.invoke('hubVersions', game),
  proxyState: (game) => ipcRenderer.invoke('proxyState', game),
  proxyRename: (game, toName, fromName) => ipcRenderer.invoke('proxyRename', game, toName, fromName),
  wizOutputs: () => ipcRenderer.invoke('wizOutputs'),
  wizSetOutput: (game, mode) => ipcRenderer.invoke('wizSetOutput', game, mode),
  wizSetConfig: (game, settings) => ipcRenderer.invoke('wizSetConfig', game, settings),
  wizGetConfig: (game) => ipcRenderer.invoke('wizGetConfig', game),
  hubAllReleases: () => ipcRenderer.invoke('hubAllReleases'),
  hubDownloadAll: () => ipcRenderer.invoke('hubDownloadAll'),
  hubPooled: () => ipcRenderer.invoke('hubPooled'),
  hubInstallInto: (game, tag) => ipcRenderer.invoke('hubInstallInto', game, tag),
  hubSuggest: (tags, games) => ipcRenderer.invoke('hubSuggest', tags, games),
  uninstall: (modId, game) => ipcRenderer.invoke('uninstall', modId, game),
  uninstallAll: (game) => ipcRenderer.invoke('uninstallAll', game),
  installedMods: (game) => ipcRenderer.invoke('installedMods', game),
  readConfig: (modId, game) => ipcRenderer.invoke('readConfig', modId, game),
  writeConfig: (modId, game, patch) => ipcRenderer.invoke('writeConfig', modId, game, patch),
  writeConfigFile: (game, rel, patch) => ipcRenderer.invoke('writeConfigFile', game, rel, patch),
  readModConfig: (game, modId) => ipcRenderer.invoke('readModConfig', game, modId),
  readModFiles: (game, pairs) => ipcRenderer.invoke('readModFiles', game, pairs),
  analyzeConfigs: (game) => ipcRenderer.invoke('analyzeConfigs', game),
  gameInfo: (exe, folder) => ipcRenderer.invoke('gameInfo', exe, folder),
  launchGame: (game) => ipcRenderer.invoke('launchGame', game),
  appUpdateApply: (assetPath, opts) => ipcRenderer.invoke('appUpdateApply', assetPath, opts),
  logPaths: () => ipcRenderer.invoke('logPaths'),
  openLogs: () => ipcRenderer.invoke('openLogs'),
  clearLogs: () => ipcRenderer.invoke('clearLogs'),
  tailLog: (which, lines) => ipcRenderer.invoke('tailLog', which, lines),
  redetectGame: (game) => ipcRenderer.invoke('redetectGame', game),
  list6dofMods: () => ipcRenderer.invoke('list6dofMods'),
  readModAnalyzed: (game, modId) => ipcRenderer.invoke('readModAnalyzed', game, modId),
  writeAnalyzed: (game, edits) => ipcRenderer.invoke('writeAnalyzed', game, edits),
  writeModFiles: (game, patch) => ipcRenderer.invoke('writeModFiles', game, patch),
  writeModConfig: (game, modId, patch) => ipcRenderer.invoke('writeModConfig', game, modId, patch),
  readConfigFile: (game, rel) => ipcRenderer.invoke('readConfigFile', game, rel),
  readHtConfig: (game) => ipcRenderer.invoke('readHtConfig', game),
  writeHtConfig: (game, patch, path) => ipcRenderer.invoke('writeHtConfig', game, patch, path),
  openHtConfig: (game) => ipcRenderer.invoke('openHtConfig', game),

  exportAllSettings: () => ipcRenderer.invoke('exportAllSettings'),
  importAllSettings: (opts) => ipcRenderer.invoke('importAllSettings', opts),
  getSettings: () => ipcRenderer.invoke('getSettings'),
  setSettings: (patch) => ipcRenderer.invoke('setSettings', patch),
  configPath: () => ipcRenderer.invoke('configPath'),
  getManualGames: () => ipcRenderer.invoke('getManualGames'),
  detectGame: (game) => ipcRenderer.invoke('detectGame', game),
  adoptMods: (game, ids) => ipcRenderer.invoke('adoptMods', game, ids),
  manualCoreStatus: () => ipcRenderer.invoke('manualCoreStatus'),
  openManualCore: (id) => ipcRenderer.invoke('openManualCore', id),
  addManualGame: (g) => ipcRenderer.invoke('addManualGame', g),
  removeManualGame: (idOrDir) => ipcRenderer.invoke('removeManualGame', idOrDir),
  getLibrary: () => ipcRenderer.invoke('getLibrary'),
  setLibrary: (games) => ipcRenderer.invoke('setLibrary', games),
  addScanRoot: () => ipcRenderer.invoke('addScanRoot'),
  removeScanRoot: (p) => ipcRenderer.invoke('removeScanRoot', p),
  pickCoreDir: () => ipcRenderer.invoke('pickCoreDir'),
  resetCoreDir: () => ipcRenderer.invoke('resetCoreDir'),
  excludeGame: (dir) => ipcRenderer.invoke('excludeGame', dir),
  unexcludeGame: (dir) => ipcRenderer.invoke('unexcludeGame', dir),
  openDataFolder: () => ipcRenderer.invoke('openDataFolder'),
  openExternal: (url) => ipcRenderer.invoke('openExternal', url),
  gameModStatus: (game, opts) => ipcRenderer.invoke('gameModStatus', game, opts),
  openHelixFix: (gameName) => ipcRenderer.invoke('openHelixFix', gameName),

  listProfiles: () => ipcRenderer.invoke('listProfiles'),
  saveProfile: (name, data) => ipcRenderer.invoke('saveProfile', name, data),
  loadProfile: (name) => ipcRenderer.invoke('loadProfile', name),
  deleteProfile: (name) => ipcRenderer.invoke('deleteProfile', name),

  mods: () => ipcRenderer.invoke('mods'),
  onProgress: (cb) => { const h = (_e, p) => cb(p); ipcRenderer.on('progress', h); return () => ipcRenderer.removeListener('progress', h); },
  onScanProgress: (cb) => { const h = (_e, p) => cb(p); ipcRenderer.on('scan-progress', h); return () => ipcRenderer.removeListener('scan-progress', h); },
  onHtUpdates: (cb) => { const h = (_e, p) => cb(p); ipcRenderer.on('ht-updates', h); return () => ipcRenderer.removeListener('ht-updates', h); }
});
